# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Kumaresan\Dev\Python\Executar\WIN.ui'
#
# Created: Mon Jan 09 11:54:55 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(774, 613)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/xhairs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_15 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/motorcycling.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dockWidget.setWindowIcon(icon1)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_batch = QtGui.QWidget()
        self.tab_batch.setObjectName(_fromUtf8("tab_batch"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_batch)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox = QtGui.QGroupBox(self.tab_batch)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.listWidget = QtGui.QListWidget(self.groupBox)
        self.listWidget.setFrameShape(QtGui.QFrame.Box)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_5.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(381, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 1, 0, 1, 1)
        self.toolButton_7 = QtGui.QToolButton(self.tab_batch)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/forbidden.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon2)
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.gridLayout_11.addWidget(self.toolButton_7, 1, 1, 1, 1)
        self.toolButton_5 = QtGui.QToolButton(self.tab_batch)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon3)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.gridLayout_11.addWidget(self.toolButton_5, 1, 2, 1, 1)
        self.pushButton_2 = QtGui.QToolButton(self.tab_batch)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushButton_2.setAutoRaise(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_11.addWidget(self.pushButton_2, 1, 3, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/hospitals.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_batch, icon4, _fromUtf8(""))
        self.tab_scripts = QtGui.QWidget()
        self.tab_scripts.setObjectName(_fromUtf8("tab_scripts"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_scripts)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(265, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 6)
        self.ui_loadedscriptpath = QtGui.QLineEdit(self.tab_scripts)
        self.ui_loadedscriptpath.setText(_fromUtf8(""))
        self.ui_loadedscriptpath.setObjectName(_fromUtf8("ui_loadedscriptpath"))
        self.gridLayout_2.addWidget(self.ui_loadedscriptpath, 0, 2, 1, 6)
        self.ui_disp_script = QtGui.QTextEdit(self.tab_scripts)
        self.ui_disp_script.setFrameShape(QtGui.QFrame.Box)
        self.ui_disp_script.setObjectName(_fromUtf8("ui_disp_script"))
        self.gridLayout_2.addWidget(self.ui_disp_script, 1, 0, 1, 9)
        self.pushButton_5 = QtGui.QPushButton(self.tab_scripts)
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 16777215))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/PI4/Icons/pi_diagona_pack/01/16/49.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_scripts)
        self.pushButton_4.setMaximumSize(QtCore.QSize(56, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/PI4/Icons/pi_diagona_pack/01/16/22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.tab_scripts)
        self.pushButton_6.setMaximumSize(QtCore.QSize(50, 16777215))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/PI3/Icons/pi_diagona_pack/02/16/09.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon7)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QToolButton(self.tab_scripts)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/ranger_station.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon8)
        self.pushButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushButton_3.setAutoRaise(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 8, 1, 1)
        self.pushButton = QtGui.QToolButton(self.tab_scripts)
        self.pushButton.setIcon(icon)
        self.pushButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushButton.setAutoRaise(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 2, 8, 1, 1)
        self.toolButton_13 = QtGui.QToolButton(self.tab_scripts)
        self.toolButton_13.setIcon(icon4)
        self.toolButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_13.setAutoRaise(True)
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.gridLayout_2.addWidget(self.toolButton_13, 2, 7, 1, 1)
        self.tabWidget.addTab(self.tab_scripts, icon3, _fromUtf8(""))
        self.tab_status = QtGui.QWidget()
        self.tab_status.setObjectName(_fromUtf8("tab_status"))
        self.gridLayout = QtGui.QGridLayout(self.tab_status)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButton_3 = QtGui.QToolButton(self.tab_status)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/movies.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon9)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout.addWidget(self.toolButton_3, 0, 0, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.tab_status)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton = QtGui.QToolButton(self.tab_status)
        self.toolButton.setIcon(icon8)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(255, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab_status)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 4)
        self.textEdit = QtGui.QTextEdit(self.tab_status)
        self.textEdit.setMinimumSize(QtCore.QSize(461, 0))
        self.textEdit.setFrameShape(QtGui.QFrame.Box)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.tab_status, icon9, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_settings)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(351, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_settings)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.scrollArea = QtGui.QScrollArea(self.tab_5)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setToolTip(_fromUtf8(""))
        self.scrollArea.setFrameShape(QtGui.QFrame.Panel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 308))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_17 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_16.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_16.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_16.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_3, 11, 0, 1, 11)
        self.listWidget_3 = QtGui.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget_3.setMinimumSize(QtCore.QSize(204, 0))
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.gridLayout_17.addWidget(self.listWidget_3, 9, 0, 1, 12)
        self.ui_basecommand = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.ui_basecommand.setObjectName(_fromUtf8("ui_basecommand"))
        self.gridLayout_17.addWidget(self.ui_basecommand, 6, 0, 1, 12)
        self.ui_mayapath = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.ui_mayapath.setObjectName(_fromUtf8("ui_mayapath"))
        self.gridLayout_17.addWidget(self.ui_mayapath, 4, 0, 1, 12)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_17.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_17.addWidget(self.label_3, 5, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.skinbox = QtGui.QComboBox(self.groupBox_2)
        self.skinbox.setMinimumSize(QtCore.QSize(127, 0))
        self.skinbox.setObjectName(_fromUtf8("skinbox"))
        self.gridLayout_6.addWidget(self.skinbox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.skinbox_2 = QtGui.QComboBox(self.groupBox_2)
        self.skinbox_2.setMinimumSize(QtCore.QSize(127, 0))
        self.skinbox_2.setObjectName(_fromUtf8("skinbox_2"))
        self.skinbox_2.addItem(_fromUtf8(""))
        self.skinbox_2.addItem(_fromUtf8(""))
        self.skinbox_2.addItem(_fromUtf8(""))
        self.skinbox_2.addItem(_fromUtf8(""))
        self.skinbox_2.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.skinbox_2, 1, 1, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_6.addWidget(self.checkBox_3, 2, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(25, 0))
        self.label_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_2, 11, 11, 1, 1)
        self.toolButton_15 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/PI2/Icons/pi_diagona_pack/03/16/04.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_15.setIcon(icon10)
        self.toolButton_15.setObjectName(_fromUtf8("toolButton_15"))
        self.gridLayout_17.addWidget(self.toolButton_15, 8, 2, 1, 1)
        self.toolButton_16 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/PI2/Icons/pi_diagona_pack/03/16/03.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_16.setIcon(icon11)
        self.toolButton_16.setObjectName(_fromUtf8("toolButton_16"))
        self.gridLayout_17.addWidget(self.toolButton_16, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_17.addWidget(self.label_12, 8, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_13.addWidget(self.scrollArea, 4, 0, 1, 1)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/snack_bar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_5, icon12, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_6 = QtGui.QLabel(self.tab_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.ui_genscpth = QtGui.QLineEdit(self.tab_6)
        self.ui_genscpth.setObjectName(_fromUtf8("ui_genscpth"))
        self.gridLayout_7.addWidget(self.ui_genscpth, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.ui_advscpth = QtGui.QLineEdit(self.tab_6)
        self.ui_advscpth.setObjectName(_fromUtf8("ui_advscpth"))
        self.gridLayout_7.addWidget(self.ui_advscpth, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_6)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 4, 0, 1, 1)
        self.ui_tmpscpth = QtGui.QLineEdit(self.tab_6)
        self.ui_tmpscpth.setObjectName(_fromUtf8("ui_tmpscpth"))
        self.gridLayout_7.addWidget(self.ui_tmpscpth, 5, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 6, 0, 1, 1)
        self.ui_processlogpath = QtGui.QLineEdit(self.tab_6)
        self.ui_processlogpath.setObjectName(_fromUtf8("ui_processlogpath"))
        self.gridLayout_7.addWidget(self.ui_processlogpath, 7, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_6)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 8, 0, 1, 1)
        self.ui_outlogpath = QtGui.QLineEdit(self.tab_6)
        self.ui_outlogpath.setObjectName(_fromUtf8("ui_outlogpath"))
        self.gridLayout_7.addWidget(self.ui_outlogpath, 9, 0, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.tab_6)
        self.toolButton_9.setAutoRaise(True)
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.gridLayout_7.addWidget(self.toolButton_9, 10, 0, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/grocery.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_6, icon13, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget_2, 0, 0, 1, 2)
        self.toolButton_6 = QtGui.QToolButton(self.tab_settings)
        self.toolButton_6.setIcon(icon8)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.gridLayout_4.addWidget(self.toolButton_6, 1, 1, 1, 1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/mechanic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_settings, icon14, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab)
        self.textEdit_2.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_2.setLineWidth(0)
        self.textEdit_2.setMidLineWidth(5)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_12.addWidget(self.textEdit_2, 0, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/coffee.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon15, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_19.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout_15.addWidget(self.dockWidget, 0, 0, 1, 4)
        self.dockWidget_2 = QtGui.QDockWidget(self.centralwidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/shopping.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dockWidget_2.setWindowIcon(icon16)
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_14 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents_2)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBox.setFrameShape(QtGui.QFrame.Box)
        self.toolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.genlstpage = QtGui.QWidget()
        self.genlstpage.setGeometry(QtCore.QRect(0, 0, 171, 447))
        self.genlstpage.setObjectName(_fromUtf8("genlstpage"))
        self.gridLayout_8 = QtGui.QGridLayout(self.genlstpage)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.ui_gensclst = QtGui.QListWidget(self.genlstpage)
        self.ui_gensclst.setFrameShape(QtGui.QFrame.Box)
        self.ui_gensclst.setFrameShadow(QtGui.QFrame.Sunken)
        self.ui_gensclst.setObjectName(_fromUtf8("ui_gensclst"))
        self.gridLayout_8.addWidget(self.ui_gensclst, 0, 0, 1, 1)
        self.toolBox.addItem(self.genlstpage, _fromUtf8(""))
        self.advlstpage = QtGui.QWidget()
        self.advlstpage.setGeometry(QtCore.QRect(0, 0, 171, 447))
        self.advlstpage.setObjectName(_fromUtf8("advlstpage"))
        self.gridLayout_9 = QtGui.QGridLayout(self.advlstpage)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.ui_advsclst = QtGui.QListWidget(self.advlstpage)
        self.ui_advsclst.setFrameShape(QtGui.QFrame.Box)
        self.ui_advsclst.setFrameShadow(QtGui.QFrame.Sunken)
        self.ui_advsclst.setObjectName(_fromUtf8("ui_advsclst"))
        self.gridLayout_9.addWidget(self.ui_advsclst, 0, 0, 1, 1)
        self.toolBox.addItem(self.advlstpage, _fromUtf8(""))
        self.tmplstpage = QtGui.QWidget()
        self.tmplstpage.setGeometry(QtCore.QRect(0, 0, 171, 447))
        self.tmplstpage.setObjectName(_fromUtf8("tmplstpage"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tmplstpage)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.ui_tmpsclst = QtGui.QListWidget(self.tmplstpage)
        self.ui_tmpsclst.setFrameShape(QtGui.QFrame.Box)
        self.ui_tmpsclst.setFrameShadow(QtGui.QFrame.Sunken)
        self.ui_tmpsclst.setObjectName(_fromUtf8("ui_tmpsclst"))
        self.gridLayout_10.addWidget(self.ui_tmpsclst, 0, 0, 1, 1)
        self.toolBox.addItem(self.tmplstpage, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 171, 447))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.listWidget_2 = QtGui.QListWidget(self.page_2)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_18.addWidget(self.listWidget_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.toolBox, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.gridLayout_15.addWidget(self.dockWidget_2, 0, 4, 5, 1)
        self.toolButton_8 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_8.setIcon(icon8)
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.gridLayout_15.addWidget(self.toolButton_8, 4, 0, 1, 1)
        self.toolButton_4 = QtGui.QToolButton(self.centralwidget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/Styles/Icons/Style/police.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon17)
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout_15.addWidget(self.toolButton_4, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(305, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 4, 2, 1, 1)
        self.infodisp = QtGui.QLabel(self.centralwidget)
        self.infodisp.setObjectName(_fromUtf8("infodisp"))
        self.gridLayout_15.addWidget(self.infodisp, 4, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_15.addWidget(self.label_4, 1, 0, 2, 1)
        self.displayer = QtGui.QTextEdit(self.centralwidget)
        self.displayer.setFrameShape(QtGui.QFrame.Box)
        self.displayer.setObjectName(_fromUtf8("displayer"))
        self.gridLayout_15.addWidget(self.displayer, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(3)
        QtCore.QObject.connect(self.toolButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.terminator)
        QtCore.QObject.connect(self.ui_gensclst, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.do_loadscript)
        QtCore.QObject.connect(self.ui_advsclst, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.do_loadscript)
        QtCore.QObject.connect(self.ui_tmpsclst, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.do_loadscript)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_tempsave)
        QtCore.QObject.connect(self.toolButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_clearlist)
        QtCore.QObject.connect(self.toolButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_gotoscripts)
        QtCore.QObject.connect(self.toolButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_savesettings)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_logclear)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_logsave)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.do_tabchange)
        QtCore.QObject.connect(self.toolButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_statussave)
        QtCore.QObject.connect(self.toolButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_setdefaultpath)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mysignalrunner)
        QtCore.QObject.connect(self.toolButton_13, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_gotofiles)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.mysignalrunner)
        QtCore.QObject.connect(self.skinbox, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.do_changeskin)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.do_smoothtab)
        QtCore.QObject.connect(self.skinbox_2, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.do_bgstyle)
        QtCore.QObject.connect(self.listWidget_2, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.do_pluginstart)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_newscript)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_findinscript)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_loadfreshscript)
        QtCore.QObject.connect(self.listWidget_3, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MainWindow.do_presetLoad)
        QtCore.QObject.connect(self.toolButton_16, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_presetAdd)
        QtCore.QObject.connect(self.toolButton_15, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_presetRemove)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "XecuteMaya", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Drag & Drop list of files to process", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "Clear List", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "Go Script >>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_batch), QtGui.QApplication.translate("MainWindow", "File(s)  to Process", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_13.setText(QtGui.QApplication.translate("MainWindow", "<< Go Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scripts), QtGui.QApplication.translate("MainWindow", "Script Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "Output Log", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "Clear Output Log", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "Save Output Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_status), QtGui.QApplication.translate("MainWindow", "Output Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Auto Save output log", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Auto Clear output log", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Display Executing CommandLine", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_basecommand.setText(QtGui.QApplication.translate("MainWindow", "-noAutoloadPlugins -script [SCRIPTFILE] -file [MBFILE]", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_mayapath.setText(QtGui.QApplication.translate("MainWindow", "C:\\Program Files\\Autodesk\\Maya2009\\bin\\mayabatch.exe", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Executable Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Visual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Color Theme:", None, QtGui.QApplication.UnicodeUTF8))
        self.skinbox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.skinbox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.skinbox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.skinbox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.skinbox_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Smooth Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Skin:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_15.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_16.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Presets:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "General Script Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_genscpth.setText(QtGui.QApplication.translate("MainWindow", "D:\\Kumaresan\\PMF\\Scripts\\General Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Advance Script Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_advscpth.setText(QtGui.QApplication.translate("MainWindow", "D:\\Kumaresan\\PMF\\Scripts\\Advance Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Temp Scripts:", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_tmpscpth.setText(QtGui.QApplication.translate("MainWindow", "D:\\Kumaresan\\PMF\\Scripts\\Temp Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Status Log Save Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_processlogpath.setText(QtGui.QApplication.translate("MainWindow", "D:\\Kumaresan\\PMF\\Scripts\\General Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Output Log Save Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_outlogpath.setText(QtGui.QApplication.translate("MainWindow", "D:\\Kumaresan\\PMF\\Scripts\\Advance Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_9.setText(QtGui.QApplication.translate("MainWindow", "Set Default Path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#55007f;\">XecuteMAYA </span><span style=\" font-size:9pt; font-weight:600; color:#55007f;\">v2.0</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<hr />\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; text-decoration: underline; color:#55007f;\">How to Use:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Step1:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Make sure you copied entire folder structure of </span><span style=\" font-size:9pt; font-weight:600;\">XecuteMaya</span><span style=\" font-size:9pt;\"> Program to your local drive and its location is writable.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Step2:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Make sure maya has been installed properly. and check the XM\'s &quot;Settings&quot; tab for specifying its location. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Default is: C:\\Program Files\\Autodesk\\Maya2009\\bin\\mayabatch.exe</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Step2:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Drag/Drop maya files into &quot;File(s) to Process&quot; section.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Step3:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Double click any script on tool box to Load it to XM\'s Script Editor.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Step4:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Click &quot;Run&quot; to Start the process.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<hr />\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; text-decoration: underline;\">Outputs:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Output Log tab will display the outputs of active running maya process for each file. You can save them for later review.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Status Log window will display the outputs of XM\'s actions. This will indicate the XM current status and activities.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<hr />\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; text-decoration: underline;\">For Advance Users:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">How XM works?</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">XM isn\'t much deal! It make use of mayabatch.exe and execute them with the maya file you provided in the list and also it adds the script file you loaded through the command line. Outputs are captured from DOS and displayed online. That\'s it!</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Command Line available in Settings tab can be customized for advanced use! Use:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[SCRIPTFILE] - While executing this will be replaced with Script file you have been loaded!</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[MBFILE] - While executing this will be replaced with the maya file one by </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[MBFILE] - Filename with path and ext. Eg: c:\\dd\\abcde.mb</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[MBFILENAME] - Filename with ext. Eg: abcde.mb</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[MBFILENAME-NOEXT] - Filename with no ext. Eg: abcde</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[MBFILEEXT] - Fileextension alone Eg: .mb</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[MBFILEPATH] - Filepath alone Eg: c:\\dd</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">* For normal use leave it as default</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">(-noAutoloadPlugins -script [SCRIPTFILE] -file [MBFILE])</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">* For advance use you can modify this </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">(Eg: -noAutoloadPlugins -archive -file [MBFILE])</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">You can also change Exepath and CommandLine as you like. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">For example XM Application can be changed as a batch rendering tool. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Exepath:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">C:\\Program Files\\Autodesk\\Maya2009\\bin\\render.exe</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">CommandLine:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">-r sw -pre [SCRIPTFILE] [MBFILE] </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">You can even configure your own commandline application for pass your files as argument to them!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> </span></p>\n"
"<hr />\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Why XM? </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">For various simple activities, I don\'t want to waste my time opening each file in Maya UI where GL loads and reconnects, building complex maya scene file hierarchy. Because most of my automation are to extract maya node info, set/reset their node values, add/remove nodes, optimize files. etc. So definitely I don\'t want GL Viewports. This made me to use MAYABATCH. And Instead of fixing with predefined scripts. I decided to make room to add more script and customize for future. So I though of building a tool in which you can manage your MEL scripts and make it run on your may files and do the job. And also  Outputs like error message and print information of maya should be viewed/captured and logged properly. Putting all these features into one pack with additional features like portable, independent of maya version and independent of WinOS. I created the small tool called XecuteMaya. <br /><br />Few general task I used XM for...<br />* Changing file texture path for large number of files without opening them one by one. <br />* Listing unnecessary nodes, removing and optimizing them in bulk. <br />* From various files grabbing important details like RENDER SETTINGS, LAYER INFOS, CAMERA INFOS, CHARACTER INFOS.<br />* Setting / Resetting values for all files without opening them. <br />* Some times I configure XM to make it render files.<br />* And also I used it in situations like rescuing a partial damaged file by doing postmortem.<br />* I made it easy to tweak for each project pipeline and production pipeline.<br /><br />Hope, You may like it. <br />Feel free to contact me with your new ideas and suggestions!<br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"><br /></span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">XecuteMaya - v2b</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">version 2.0 (Beta)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">For supporting 3D artist around the world with easy interface for maya automation.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">by</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Kumaresan Lakshmanan</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Raja Vijayaraman</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Praveen Venkatraman</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Muthu Kumaran</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Licence</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://opensource.org/licenses/Python-2.0\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Python License (Python-2.0)</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; text-decoration: underline; color:#0000ff;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Links</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Project Home: </span><a href=\"https://groups.google.com/group/projectlra\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">http://code.google.com/p/lra/</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Discussion:</span><span style=\" font-size:8pt; font-weight:600;\"> </span><a href=\"https://groups.google.com/group/projectlra\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://groups.google.com/group/projectlra</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Help:</span><span style=\" font-size:8pt; font-weight:600;\"> </span><a href=\"http://code.google.com/p/lra/wiki/UserDocument\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">http://code.google.com/p/lra/wiki/UserDocument</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Report Issues: </span><a href=\"http://code.google.com/p/lra/issues/list\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">http://code.google.com/p/lra/issues/list</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Contact</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"mailto:projectlra@googlegroups.com\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">projectlra@googlegroups.com</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "About XM", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tool Box", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_gensclst.setSortingEnabled(False)
        self.toolBox.setItemText(self.toolBox.indexOf(self.genlstpage), QtGui.QApplication.translate("MainWindow", "General Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_advsclst.setSortingEnabled(True)
        self.toolBox.setItemText(self.toolBox.indexOf(self.advlstpage), QtGui.QApplication.translate("MainWindow", "Advance Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.ui_tmpsclst.setSortingEnabled(True)
        self.toolBox.setItemText(self.toolBox.indexOf(self.tmplstpage), QtGui.QApplication.translate("MainWindow", "Temp Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Customized Mel Generators", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "Save Status Log", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "Terminate Process", None, QtGui.QApplication.UnicodeUTF8))
        self.infodisp.setText(QtGui.QApplication.translate("MainWindow", "Ready!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "XM\'s Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayer.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">XM is Idle</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">- Submit maya file(s).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">- Select a script to be processed on it.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">- Click RUN to execute.<br /><br /></span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import Res_rc
